code-review:
  stage: test
  tags:
    - fe-shell
  script:
    - npm ci
    - npm run lint
    - npm run test
    - echo "推送代码到 github..."
    - if [ "$(git remote add github git@github.com:FED-CLUB/example.git)" ]; then echo "ok"; fi;
    - git config user.name fed-bot
    - git config user.email fed-bot@isyscore.com
    - git checkout v1.x
    - git pull origin v1.x
    - git push --set-upstream github v1.x
    - echo "推送成功，请订阅 github 上的工作流状态"
  only:
    - v1.x
