name: code-review

on:
  push

jobs:
  corde-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: echo "npm ci"
      - run: echo "代码格式检查"
      - run: echo "代码单元测试"
