name: github-release

on:
  push:
    tags:
      - v*.*.*

jobs:
  create-github-release:
    needs: project-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: git_tag
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - run: git branch
      - run: git tag --list
      - run: git tag --points-at HEAD --list "v*"
      - run: cat package.json
      - run: echo ${{ steps.git_tag.outputs.VERSION }}
      - run: echo ${{ toJSON(github) }}
  #     - uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         GIT_VERSION: ${{ steps.git_tag.outputs.VERSION }}
  #       with:
  #         tag_name: ${{ env.GIT_VERSION }}
  #         release_name: Release ${{ env.GIT_VERSION }}
  #         draft: false
  #         prerelease: false
  #         body: "[更新日志](https://github.com/${{ github.repository }}/blob/${{ env.GIT_VERSION }}/CHANGELOG.md)"

